### PR TITLE
Generic codes to AtomsCalculatorsUtils and Update to AC@0.2

### PR DESCRIPTION
**Pull request by cortner**
- [x] translate the SW codes
- [x] translate the pair potential codes 
- [x] incorporate FD tests

### Future PRs

- in-place interface

### CODE REVIEW

**Comment by cortner** [comment]
the pair potentials tests are failing. For the parameterized this is fine because I haven't moved the parameterized calling conventions since they are inconsistent with the new interface. 

But for the simple pair potential this is very odd since the calculator is returning all the right units but the AtomsCalculators consistency test suggests that the units are incorrect. 

@tjjarvinen  -- please look into this.

**Comment by tjjarvinen** [comment]
The issue is probably with the functions you moved from `EmpiricalPotentials` to `AtomsUtilityCalculators`. You have imported them, but something there does not work.

I see atleast two errors incorrect units linking to `AtomsCalculators.promote_force_type` and dispatch not working for `ParamentricPairPotential` for `potential_energy`. I need  more time to look where this comes. So, this is an update where I am know.

**Comment by tjjarvinen** [comment]
The main problem is that when you moved site potentials to AtomsUtilityCalculators, you did not implement `AtomsAtomsCalculators.promote_force_type` for site potentials and thus they have wrong units.

That leaves out the other issue with dispatch. I will look for it tomorrow.

**Comment by cortner** [comment]
I am pretty sure I did, but maybe it got lost or not imported correctly. Thanks for tracking that down. 

My only request - please don't change the modified interface for SitePotential without discussing it with me first even if it isn't what AtomsCalculators currently expects. There are good reasons for the changes I made.

**Comment by cortner** [comment]
This was indeed the problem, I pushed a temporary fix. I am now guessing that the analogous SW test passed by accident. 

Can you briefly explain how exactly is `promote_force_type` used in `AtomsCalculators`?  Given it is just an interface I'm surprised that this is actually needed there? It feels like such a function would only needed for implementation. Probably you need it in the macro to implement the allocating interface from the in-place

**Comment by cortner** [comment]
I noticed the `promote_force_type` is not documented in AtomsCalculators. If it is part of the interface then this should probably be done.

**Comment by tjjarvinen** [comment]
The documentation describes `promote_force_type` as (in [Implementing forces section](https://juliamolsim.github.io/AtomsCalculators.jl/dev/interface-definition/#Implementing-forces-call))

> Same way `AtomsCalculators.promote_force_type(system, calculator)` creates a force type for the calculator for given input that can be used to allocate force data. You can also allocate for some other type, of your choosing or use the default one. You can overload `promote_force_type` for your force type, this is automatically used by `zero_forces` command to change the element type. If you wan to change array type overload `zero_forces` for your calculator.

But, yes documentation needs improvement. This was postponed to the lux update...

So, basically you use `promote_force_type` to get information on what is element type for forces with given system and calculator.

**Comment by cortner** [comment]
with the latest updates this PR now adresses #23

**Comment by cortner** [comment]
This PR only needs AtomsCalculatorsUtilities#18 merged and registered, then it should be ready.

**Comment by cortner** [comment]
@tjjarvinen  -- this is the next PR as soon as ACU 0.2.0 is registered.

**Comment by cortner** [comment]
@tjjarvinen -- I'd like to merge and register this asap. If you have anything blocking please let me know tonight.

**Comment by tjjarvinen** [comment]
No blockers from my side. We can always fix the issues after registration has been completed.

**Pull request merged**
