### PR TITLE
support AtomsBase v0.4

### PR DESCRIPTION
**Pull request by tjjarvinen**

### CODE REVIEW

**Comment by cortner** [comment]
thank you. Doesn't this need updates to AtomsCalculatorsUtilities first though?  In particular issue ACU issue # 9

**Comment by tjjarvinen** [comment]
The tests need the new version to run properly. It does pass on my computer with correct versions though

**Comment by cortner** [comment]
Well, they will pass here as well because they will just install the old ACU which restricts AB to < 0.4. So I prefer to first update ACU to be AB 0.4 compatible (even if it means a breaking change) and then come back to this PR?

**Comment by tjjarvinen** [comment]
Yes I am doing that atm. ACU will be tagged new release once the CI passes. Then I will come to this.

There is also a bug with Lennard-Jones potential, so I try to get in a fix for that too.

**Comment by cortner** [comment]
great, thank you.

**Comment by tjjarvinen** [comment]
AtomsBuilder needs an update too, to get the tests run on ABv04

**Comment by cortner** [comment]
> AtomsBuilder needs an update too

about to be merged into General

**Pull request merged**
